Controllers films users
mikadim/java-filmorate pull request #3
Opened 2022-12-03 22:45 UTC by mikadim

2022-12-04 10:41 UTC, Frilock requested changes
Добрый день, интересное решение, подошли к задаче не формально, поэтому на самом деле ее довольно усложнили. Написал ряд комментариев, но они в целом не особо большие. В целом работа хорошая, жду новую версию

2022-12-04 10:41 UTC, Frilock commented on pom.xml
> +            <version>6.1.6.Final</version>
Версии библиотек правильнее указывать в одном месте, а именно, в properties, чтобы при смене версии не приходилось лазить по иногда большому pom файлу.
Давайте как и другие вынесем

2022-12-04 10:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PostMapping()
Пустые скобки можно не писать

2022-12-04 10:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/dto/UserRequestDto.java
> +    @Email
По моему перебор аннотаций, например, @NotNull - аннотированный элемент не должен быть null. Принимает любой тип. @NotBlank - аннотированный элемент не должен быть null и должен содержать хотя бы один не пробельный символ. Принимает CharSequence.@NotEmpty - аннотированный элемент не должен быть null или пустым. Разве они друг друга не дублируют?

2022-12-04 10:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/dto/UserRequestDto.java
> +public class UserRequestDto {
А вы lombok специально использовать не стали? Вроде добавляет довольно много "синтаксического сахара"

2022-12-04 10:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/validator/UserValidator.java
> +        if (userRequestDto.getName() == null || userRequestDto.getName().isBlank() || userRequestDto.getName().isEmpty()) {
Эту проверку можно заменить на StringUtils.isBlank(...) - от apache common библиотека

2022-12-04 10:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/converter/FilmRequestDtoToFilm.java
> +    public Film convert(FilmRequestDto dto) {
А не нужно проверять что dto != null?

2022-12-04 10:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        // User user = userMapper.mapToUser(dto);
Закомментированный код надо убрать

2022-12-04 10:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @DeleteMapping (value = "/clearfortest")
перед ( не нужен пробел

2022-12-04 10:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        idGenerator=new UserIdGenerator();
= с двух сторон пробелом обособляется

2022-12-04 10:41 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +@ComponentScan(basePackages = "ru.yandex.practicum")
По моему это можно не указывать, и так бины найден. Или у вас без этого не проходят тесты?

2022-12-04 10:41 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    @Order(1)
А вам порядок принципиален или просто чтоб красиво вывести описание сделали?

2022-12-04 10:41 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/validator/FilmValidatorTest.java
> +    FilmRequestDto filmRequestDto;
Модификатор забыли

2022-12-07 22:14 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PostMapping()
забыл убрать просто, это все эксперименты над кодом были

2022-12-07 22:41 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/controller/dto/UserRequestDto.java
> +    @Email
почитал, действительно борщ получился. Можно вопрос? описание библиотеки я нагуглил (https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints) А есть какой то способ в идее быстро найти за что отвечает аннотация (библиотеку я саму нашел в идее, но полезной инфы там не увидел)

2022-12-07 22:48 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/controller/dto/UserRequestDto.java
> +public class UserRequestDto {
использовал конечно... только когда начались тесты пришли и проблемы из-за этого lombok. Вообще у меня там куча проблем вылезло, но касаемо lombok я 100% проверил, когда уже все работало, отдал ему генерацию методов и прочего, и снова тесты не работали.

2022-12-07 23:18 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/controller/validator/UserValidator.java
> +        if (userRequestDto.getName() == null || userRequestDto.getName().isBlank() || userRequestDto.getName().isEmpty()) {
благодарю! мельком как то уже попадалась она, выпала из памяти

2022-12-10 10:51 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/controller/converter/FilmRequestDtoToFilm.java
> +    public Film convert(FilmRequestDto dto) {
я сейчас конечно добавил проверку, но) при отправке запроса без тела, spring до нее похоже не доходит и возвращает BadRequest вот отсюда (@RequestBody @Valid @NotNull FilmRequestDto dto). А по другому вроде null в этот конвертор и не попадает... Или это с целью расширения приложения и вдруг где то еще будут использовать эту конвертацию?

2022-12-10 10:54 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        idGenerator=new UserIdGenerator();
блин, вроде везде автоформат сделал перед отправкой...

2022-12-10 10:59 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +@ComponentScan(basePackages = "ru.yandex.practicum")
да, у меня были проблемы с тестами поэтому я уже ставил все что где то видел
сейчас без @ComponentScan(basePackages = "ru.yandex.practicum") проверил, работает, поэтому ок убираем

2022-12-10 11:01 UTC, mikadim commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    @Order(1)
вообще изначально просто попробовать хотел))) а потом оказалось что из-за put порядок тоже важен

2022-12-10 14:57 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/dto/UserRequestDto.java
> +    @Email
Наверно нет, по крайней мере я не знаю, только внутрь провалиться через cntrl + ПКМ и там полазить и самому понять. Либо документацию читать, что скорее всего будет самым нормальным вариантом

2022-12-10 14:57 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/converter/FilmRequestDtoToFilm.java
> +    public Film convert(FilmRequestDto dto) {
Ну да все верно, был вопрос с подвохом =)

2022-12-10 14:58 UTC, Frilock approved these changes
Принято, успехов дальше

2022-12-11 10:43 UTC, merged