feat: добавление лайков и друзей
mikadim/java-filmorate pull request #4
Opened 2022-12-12 21:02 UTC by mikadim

2022-12-13 17:47 UTC, Frilock requested changes
Добрый день, указал комментарий по работе со слоями приложения, жду новую версию

2022-12-13 17:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage storage;
Смотрите, возможно покажется странным, но когда вы работаете с большим веб приложением, необходимо придерживаться определенной логики. Смотрите, правильно "инжектить" бины по такому правилу
В контролер - сервисы - в сервисы хранилища. То есть в контролере вызывать хранилище не правильно, сделайте такой же метод в сервисе и в контролере вызывайте его

2022-12-13 17:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/utils/FilmIdGenerator.java
> +@Component()
пустые скобки не нужны

2022-12-13 17:47 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    @Order(6)
Вообще, на будущее порядок выполнения тестов не должен влиять на их прохождение

2022-12-13 17:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/converter/UserRequestDtoToUser.java
> +        if (dto.getFriends() != null) {
По идее чтоб так не делать можно в классах модели сразу инициализировать коллекцию

2022-12-18 17:11 UTC, mikadim commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    @Order(6)
дельное замечание, убрал

2022-12-18 17:29 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/controller/converter/UserRequestDtoToUser.java
> +        if (dto.getFriends() != null) {
я метался как лучше будет, подумал что раз дата обжект делает объект, путь он всем и занимается) ок, перенес в модели

2022-12-18 19:29 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage storage;
принято, контроллер-сервис, сервис-сторадж!

2022-12-19 17:30 UTC, Frilock requested changes
Добрый вечер, оставил несколько комментариев, но в основном это "допрос с пристрастием" к оформлению кода, изменений должно быть не много, а так в целом молодцы. Жду новую версию

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          return new ResponseEntity<Film>(film, HttpStatus.OK);
<Film> - Film внутри скобок можно не указывать

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      private final FilmMapper filmMapper;
private final FilmMapper filmMapper;
    private final ConversionService conversionService;

Данные бины не используются в данном классе, их нужно удалить

Получается вроде как сам FilmMapper не нужен как класс

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public ResponseEntity<Film> addFilm(@RequestBody @Valid @NotNull FilmRequestDto dto) {
А Validated над контроллером не нужно? У Вас валидация отработает?

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      private static final Logger log = LoggerFactory.getLogger(UserController.class);
Внутри логгера указан не тот класс (по этому и про ломбок писал в прошлой работе, что возможно, позволяет таких вещей избегать)

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        List<Integer> collect = service.getFilms().stream().map(film -> film.getId()).collect(Collectors.toList());
Можно заменить на .map(Film::getId)

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        List<Integer> collect = service.getFilms().stream().map(film -> film.getId()).collect(Collectors.toList());
Вообще всю эту логику нужно внести в сервис, в контроллере оставить только вызов метода сервиса, например, delete

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        for (Integer id : collect) {
Кроме того, вся конструкция довольно странная, то есть вы ловите ошибку и ее игнорируете? Вообще такое допустимо в целом, но тогда исключение назовите не e, а ignored тогда не будет варнинга.
Кроме того, кажется, что лучше залогировать что то внутри блока, что мол не смогли удалить по такой то причине

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>      private final ConversionService conversionService;
Опять же лишние бины

Мапперы из пакета мапперов не используются

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        User user = service.getUser(id);
Логику надо перенести в сервис

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                .map(i -> service.getUser(i))
Можно заменить на .map(service::getUser)

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                .filter(i -> otherFiends.contains(i))
Можно заменить на                 .filter(otherFiends::contains)
Вам IDEA такое не подсказывает? Желтеньким должно выделять

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        List<Integer> collect = service.getUsers().stream().map(user -> user.getId()).collect(Collectors.toList());
Логику внутрь сервиса

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
Лишняя пустая строка

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ResponseEntity<>(Map.of("error", e.getMessage()), HttpStatus.NOT_FOUND);
Опять же давайте распространим сообщение - Такая то ошибка:

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>          return new ResponseEntity<>("проверьте тело запроса", HttpStatus.BAD_REQUEST);
П c заглавной буквы =)

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/utils/FilmIdGenerator.java
> +    public void setForTest() {
Создавать методы только для тестов не очень хорошая идея

2022-12-19 17:30 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/exception/UserStorageError.java
> +    public UserStorageError(String message) {
Под все исключения я бы создал общий пакет и их бы перенес туда, кажется, так было бы проще ориентироваться по коду

2022-12-21 19:52 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          return new ResponseEntity<Film>(film, HttpStatus.OK);
Добрый вечер Иван) с пристрастием это хорошо)

2022-12-21 21:04 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public ResponseEntity<Film> addFilm(@RequestBody @Valid @NotNull FilmRequestDto dto) {
насколько понял для моих примитивных тестов  Validated необязательно... добавил, вроде все работает как и раньше...

2022-12-21 21:06 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        List<Integer> collect = service.getFilms().stream().map(film -> film.getId()).collect(Collectors.toList());
мне в таком виде просто понятней что происходит) но раз надо то ок

2022-12-21 21:29 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        for (Integer id : collect) {
про ignored не знал, спс! тут метод не относится к бизнес задаче поэтому не заморочился... добавил лог, пишу в дебаг, так видимо то что надо.

2022-12-21 21:52 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +                .filter(i -> otherFiends.contains(i))
вообщет выделяет, но мне как то с лямбдами еще не на автомате получается разбираться, поэтому делаю чтоб максимально ясно было

2022-12-21 22:38 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/utils/FilmIdGenerator.java
> +    public void setForTest() {
дыа, знаю канеш, но мне это прямо очень нужно...

2022-12-21 22:44 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/exception/UserStorageError.java
> +    public UserStorageError(String message) {
да, я тож смотрел на проект и думал может вынести отдельно их. Вынес!

2022-12-21 23:12 UTC, mikadim commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      private final FilmMapper filmMapper;
да, бины лишние действительно... убрал. А интерфейс нужен для моих дтошек, его оставляю.

2022-12-22 06:08 UTC, Frilock approved these changes
Принято

2022-12-24 15:00 UTC, merged